#ifndef STATUS_H
#define STATUS_H

#define ALL_OK 0
#define IO_ERROR 1
#define INVALID_ARGUMENT_ERROR 2
#define NO_MEMORY_ERROR 3
#define BAD_PATH_ERROR 4 
#define FILE_SYSTEM_NOT_US_ERROR 5
#define READ_ONLY_ERROR 6
#define UNIMPLEMENTED_ERROR 7
#endif
